import type { Metadata } from "next"
import Header from "@/app/components/Header"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className="m-4 max-w-screen-md font-mono md:mx-auto lg:mx-auto">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
